# Generated by Django 3.1.8 on 2021-11-20 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0003_auto_20211120_1141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
