# Generated by Django 3.1.8 on 2021-11-23 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0005_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
