# Generated by Django 3.1.8 on 2021-11-24 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0007_approvals'),
    ]

    operations = [
        migrations.DeleteModel(
            name='approvals',
        ),
    ]
